# Generated by Django 2.2.2 on 2019-07-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=200)),
                ('lastname', models.CharField(default=None, max_length=200)),
                ('title', models.CharField(default=None, max_length=200)),
                ('tags', models.CharField(default=None, max_length=100)),
                ('about', models.TextField(default=None)),
                ('image', models.ImageField(default=None, upload_to='images')),
            ],
        ),
    ]
