# Generated by Django 2.2.2 on 2019-07-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='bestreply',
            field=models.IntegerField(default=0),
        ),
    ]
